{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Amazon ML Challenge 2026 - Task 1\n",
    "\n",
    "Training-only exploratory analysis for positive ground-truth entity-resolution matches. This notebook intentionally stops before candidate generation, fuzzy matching, embeddings, blocking, thresholds, or model training."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from pathlib import Path\n",
    "import re\n",
    "from collections import Counter\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from IPython.display import display\n",
    "\n",
    "RANDOM_STATE = 42\n",
    "\n",
    "pd.set_option(\"display.max_columns\", 120)\n",
    "pd.set_option(\"display.max_colwidth\", 140)\n",
    "\n",
    "\n",
    "def resolve_train_path(filename):\n",
    "    \"\"\"Find train TSV files in Colab-style or local project layouts.\"\"\"\n",
    "    candidates = [\n",
    "        Path(\"/content\") / filename,\n",
    "        Path(\"/content/student_resource/dataset/train\") / filename,\n",
    "        Path.cwd() / filename,\n",
    "        Path.cwd() / \"student_resource\" / \"dataset\" / \"train\" / filename,\n",
    "        Path(\"/Users/vangashashankgoud/Documents/ChatGPT/Amazon ML challenge 2026/student_resource/dataset/train\") / filename,\n",
    "    ]\n",
    "    for path in candidates:\n",
    "        if path.exists():\n",
    "            return path\n",
    "    searched = \"\\n\".join(str(path) for path in candidates)\n",
    "    raise FileNotFoundError(f\"Could not find {filename}. Searched:\\n{searched}\")\n",
    "\n",
    "\n",
    "train_paths = {\n",
    "    \"s1\": resolve_train_path(\"train_source1.tsv\"),\n",
    "    \"s2\": resolve_train_path(\"train_source2.tsv\"),\n",
    "    \"s3\": resolve_train_path(\"train_source3.tsv\"),\n",
    "    \"gt\": resolve_train_path(\"train_ground_truth.tsv\"),\n",
    "}\n",
    "\n",
    "print(\"Using TRAIN files only:\")\n",
    "for name, path in train_paths.items():\n",
    "    print(f\"{name}: {path}\")\n",
    "\n",
    "s1 = pd.read_csv(train_paths[\"s1\"], sep=\"\\t\")\n",
    "s2 = pd.read_csv(train_paths[\"s2\"], sep=\"\\t\")\n",
    "s3 = pd.read_csv(train_paths[\"s3\"], sep=\"\\t\")\n",
    "gt = pd.read_csv(train_paths[\"gt\"], sep=\"\\t\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 1 - Inspect Train Schemas\n",
    "\n",
    "Print each training DataFrame's shape, columns, first rows, and `info()` output. Do not assume any business-name/address/phone/domain column names."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_frames = {\n",
    "    \"Source 1 train\": s1,\n",
    "    \"Source 2 train\": s2,\n",
    "    \"Source 3 train\": s3,\n",
    "    \"Ground truth train\": gt,\n",
    "}\n",
    "\n",
    "\n",
    "def inspect_schema(label, df):\n",
    "    print(\"=\" * 80)\n",
    "    print(label)\n",
    "    print(\"shape:\", df.shape)\n",
    "    print(\"columns:\", df.columns.tolist())\n",
    "    print(\"\\nhead:\")\n",
    "    display(df.head())\n",
    "    print(\"\\ninfo:\")\n",
    "    df.info()\n",
    "    print(\"\\nmissing values:\")\n",
    "    display(df.isna().sum().to_frame(\"missing_count\"))\n",
    "\n",
    "\n",
    "for label, df in train_frames.items():\n",
    "    inspect_schema(label, df)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 2 - Reproducible Positive-Match Sample\n",
    "\n",
    "Create a 25-entity sample from the training ground truth using `random_state=42`: 5 with 1 match, 5 with 2 matches, 10 with 3-5 matches, and 5 with 6+ matches. The original `gt` DataFrame is not modified."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def parse_matched_ids(value):\n",
    "    if pd.isna(value):\n",
    "        return []\n",
    "    return [entity_id.strip() for entity_id in str(value).split(\",\") if entity_id.strip()]\n",
    "\n",
    "\n",
    "def count_matched_ids(value):\n",
    "    return len(parse_matched_ids(value))\n",
    "\n",
    "\n",
    "# Keep the original ground-truth DataFrame unchanged for later work.\n",
    "gt_task1 = gt.copy()\n",
    "gt_task1[\"match_count\"] = gt_task1[\"matched_entity_ids\"].map(count_matched_ids)\n",
    "\n",
    "print(\"match_count distribution:\")\n",
    "display(gt_task1[\"match_count\"].value_counts().sort_index().to_frame(\"row_count\"))\n",
    "\n",
    "print(\"match_count summary:\")\n",
    "display(gt_task1[\"match_count\"].describe().to_frame(\"match_count\"))\n",
    "\n",
    "print(\"Grouped counts:\")\n",
    "print(\"0 matches:\", int((gt_task1[\"match_count\"] == 0).sum()))\n",
    "print(\"1 match:  \", int((gt_task1[\"match_count\"] == 1).sum()))\n",
    "print(\"2 matches: \", int((gt_task1[\"match_count\"] == 2).sum()))\n",
    "print(\"3+ matches:\", int((gt_task1[\"match_count\"] >= 3).sum()))\n",
    "\n",
    "source_counts = Counter()\n",
    "for ids_text in gt_task1[\"matched_entity_ids\"].dropna():\n",
    "    for entity_id in parse_matched_ids(ids_text):\n",
    "        if entity_id.startswith(\"S2-\"):\n",
    "            source_counts[\"S2\"] += 1\n",
    "        elif entity_id.startswith(\"S3-\"):\n",
    "            source_counts[\"S3\"] += 1\n",
    "        else:\n",
    "            source_counts[\"Other/unknown\"] += 1\n",
    "\n",
    "print(\"Matched-ID source counts:\")\n",
    "display(pd.Series(source_counts, name=\"positive_link_count\").to_frame())\n",
    "\n",
    "\n",
    "def sample_match_count_group(mask, n, label):\n",
    "    pool = gt_task1.loc[mask].copy()\n",
    "    if len(pool) < n:\n",
    "        raise ValueError(f\"Need {n} rows for {label}, but only found {len(pool)}\")\n",
    "    sampled = pool.sample(n=n, random_state=RANDOM_STATE).copy()\n",
    "    sampled.insert(0, \"sample_group\", label)\n",
    "    return sampled\n",
    "\n",
    "\n",
    "sample_entities = pd.concat(\n",
    "    [\n",
    "        sample_match_count_group(gt_task1[\"match_count\"] == 1, 5, \"exactly_1_match\"),\n",
    "        sample_match_count_group(gt_task1[\"match_count\"] == 2, 5, \"exactly_2_matches\"),\n",
    "        sample_match_count_group(gt_task1[\"match_count\"].between(3, 5), 10, \"3_to_5_matches\"),\n",
    "        sample_match_count_group(gt_task1[\"match_count\"] >= 6, 5, \"6plus_matches\"),\n",
    "    ],\n",
    "    ignore_index=True,\n",
    ")\n",
    "\n",
    "sample_entities[\"matched_id_list\"] = sample_entities[\"matched_entity_ids\"].map(parse_matched_ids)\n",
    "\n",
    "print(\"Sampled Source-1 entities:\")\n",
    "display(sample_entities[[\"sample_group\", \"source1_entity_id\", \"matched_entity_ids\", \"match_count\"]])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Steps 3-4 - Retrieve Complete Records and Build Pairwise Inspection Rows\n",
    "\n",
    "For every sampled Source-1 entity, retrieve its full S1 record and every positive S2/S3 ground-truth match. The pairwise DataFrame includes semantic fields only when they exist, plus any extra discovered attributes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "ID_CANDIDATES = [\"entity_id\", \"id\", \"business_id\", \"record_id\"]\n",
    "FIELD_CANDIDATES = {\n",
    "    \"name\": [\"business_name\", \"name\", \"company_name\", \"entity_name\", \"organization_name\", \"legal_name\", \"store_name\"],\n",
    "    \"address\": [\"business_address\", \"address\", \"street_address\", \"full_address\", \"addr\", \"location_address\"],\n",
    "    \"city\": [\"city\", \"business_city\", \"locality\", \"town\"],\n",
    "    \"state\": [\"state\", \"province\", \"region\", \"business_state\"],\n",
    "    \"country\": [\"country\", \"business_country\", \"country_code\"],\n",
    "    \"postal_code\": [\"postal_code\", \"postcode\", \"zip\", \"zip_code\", \"business_postal_code\"],\n",
    "    \"phone\": [\"phone\", \"phone_number\", \"telephone\", \"business_phone\", \"contact_phone\"],\n",
    "    \"website\": [\"website\", \"url\", \"domain\", \"business_website\", \"homepage\", \"web_site\"],\n",
    "}\n",
    "KEY_ROLES = [\"name\", \"address\", \"city\", \"state\", \"country\", \"postal_code\", \"phone\", \"website\"]\n",
    "\n",
    "\n",
    "def find_first_column(columns, candidates):\n",
    "    lower_to_original = {str(col).lower(): col for col in columns}\n",
    "    for candidate in candidates:\n",
    "        if candidate.lower() in lower_to_original:\n",
    "            return lower_to_original[candidate.lower()]\n",
    "    return None\n",
    "\n",
    "\n",
    "def detect_id_column(df, label):\n",
    "    col = find_first_column(df.columns, ID_CANDIDATES)\n",
    "    if col is None:\n",
    "        raise ValueError(f\"Could not detect an ID column for {label}. Columns: {df.columns.tolist()}\")\n",
    "    return col\n",
    "\n",
    "\n",
    "def detect_field_map(df):\n",
    "    field_map = {}\n",
    "    for role, candidates in FIELD_CANDIDATES.items():\n",
    "        col = find_first_column(df.columns, candidates)\n",
    "        if col is not None:\n",
    "            field_map[role] = col\n",
    "    return field_map\n",
    "\n",
    "\n",
    "id_cols = {\n",
    "    \"S1\": detect_id_column(s1, \"Source 1\"),\n",
    "    \"S2\": detect_id_column(s2, \"Source 2\"),\n",
    "    \"S3\": detect_id_column(s3, \"Source 3\"),\n",
    "}\n",
    "field_maps = {\n",
    "    \"S1\": detect_field_map(s1),\n",
    "    \"S2\": detect_field_map(s2),\n",
    "    \"S3\": detect_field_map(s3),\n",
    "}\n",
    "\n",
    "print(\"Detected ID columns:\")\n",
    "display(pd.Series(id_cols, name=\"id_column\").to_frame())\n",
    "\n",
    "print(\"Detected semantic field columns:\")\n",
    "display(pd.DataFrame(field_maps).fillna(\"\"))\n",
    "\n",
    "# Index copies for lookup; original DataFrames remain unchanged.\n",
    "s1_by_id = s1.set_index(id_cols[\"S1\"], drop=False)\n",
    "s2_by_id = s2.set_index(id_cols[\"S2\"], drop=False)\n",
    "s3_by_id = s3.set_index(id_cols[\"S3\"], drop=False)\n",
    "source_lookup = {\"S2\": s2_by_id, \"S3\": s3_by_id}\n",
    "\n",
    "\n",
    "def lookup_record(indexed_df, entity_id):\n",
    "    if entity_id not in indexed_df.index:\n",
    "        return None, 0\n",
    "    record = indexed_df.loc[entity_id]\n",
    "    if isinstance(record, pd.DataFrame):\n",
    "        return record.iloc[0], len(record)\n",
    "    return record, 1\n",
    "\n",
    "\n",
    "def source_from_entity_id(entity_id):\n",
    "    if str(entity_id).startswith(\"S2-\"):\n",
    "        return \"S2\"\n",
    "    if str(entity_id).startswith(\"S3-\"):\n",
    "        return \"S3\"\n",
    "    return \"unknown\"\n",
    "\n",
    "\n",
    "def add_semantic_fields(row, prefix, record, field_map):\n",
    "    for role in KEY_ROLES:\n",
    "        col = field_map.get(role)\n",
    "        if col is not None:\n",
    "            row[f\"{prefix}_{role}\"] = record.get(col, np.nan)\n",
    "\n",
    "\n",
    "def add_extra_fields(row, prefix, record, field_map, id_col):\n",
    "    mapped_cols = set(field_map.values()) | {id_col}\n",
    "    for col in record.index:\n",
    "        if col not in mapped_cols:\n",
    "            row[f\"{prefix}_{col}\"] = record.get(col, np.nan)\n",
    "\n",
    "\n",
    "pairwise_rows = []\n",
    "lookup_issues = []\n",
    "\n",
    "for _, sample_row in sample_entities.iterrows():\n",
    "    s1_id = sample_row[\"source1_entity_id\"]\n",
    "    s1_record, s1_hits = lookup_record(s1_by_id, s1_id)\n",
    "    matched_ids = sample_row[\"matched_id_list\"]\n",
    "\n",
    "    if s1_record is None:\n",
    "        lookup_issues.append({\"entity_id\": s1_id, \"issue\": \"S1 ID missing from Source 1 train\"})\n",
    "        continue\n",
    "\n",
    "    if s1_hits > 1:\n",
    "        lookup_issues.append({\"entity_id\": s1_id, \"issue\": f\"S1 ID has {s1_hits} duplicate rows; first row used\"})\n",
    "\n",
    "    for matched_id in matched_ids:\n",
    "        matched_source = source_from_entity_id(matched_id)\n",
    "        if matched_source not in source_lookup:\n",
    "            lookup_issues.append({\"entity_id\": matched_id, \"issue\": \"Matched ID source is not S2 or S3\"})\n",
    "            continue\n",
    "\n",
    "        matched_record, matched_hits = lookup_record(source_lookup[matched_source], matched_id)\n",
    "        if matched_record is None:\n",
    "            lookup_issues.append({\"entity_id\": matched_id, \"issue\": f\"ID missing from Source {matched_source[-1]} train\"})\n",
    "            continue\n",
    "\n",
    "        if matched_hits > 1:\n",
    "            lookup_issues.append({\"entity_id\": matched_id, \"issue\": f\"Matched ID has {matched_hits} duplicate rows; first row used\"})\n",
    "\n",
    "        row = {\n",
    "            \"sample_group\": sample_row[\"sample_group\"],\n",
    "            \"s1_entity_id\": s1_id,\n",
    "            \"matched_entity_id\": matched_id,\n",
    "            \"matched_source\": matched_source,\n",
    "            \"match_count\": int(sample_row[\"match_count\"]),\n",
    "        }\n",
    "        add_semantic_fields(row, \"s1\", s1_record, field_maps[\"S1\"])\n",
    "        add_semantic_fields(row, \"matched\", matched_record, field_maps[matched_source])\n",
    "        add_extra_fields(row, \"s1_extra\", s1_record, field_maps[\"S1\"], id_cols[\"S1\"])\n",
    "        add_extra_fields(row, \"matched_extra\", matched_record, field_maps[matched_source], id_cols[matched_source])\n",
    "        pairwise_rows.append(row)\n",
    "\n",
    "pairwise_inspection = pd.DataFrame(pairwise_rows)\n",
    "lookup_issues_df = pd.DataFrame(lookup_issues)\n",
    "\n",
    "print(\"Pairwise inspection shape:\", pairwise_inspection.shape)\n",
    "display(pairwise_inspection.head(20))\n",
    "\n",
    "print(\"Lookup issues:\")\n",
    "if lookup_issues_df.empty:\n",
    "    print(\"No lookup issues found for the sampled positive matches.\")\n",
    "else:\n",
    "    display(lookup_issues_df)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 5 - Simple Normalized Exact-Match Indicators\n",
    "\n",
    "Use only basic normalization: lowercase, strip/collapse whitespace, remove obvious punctuation for text, digit-only phone normalization, and simple URL/domain cleanup."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def is_missing(value):\n",
    "    return pd.isna(value) or str(value).strip() == \"\"\n",
    "\n",
    "\n",
    "def normalize_text(value, remove_punctuation=True):\n",
    "    if is_missing(value):\n",
    "        return \"\"\n",
    "    text = str(value).lower().strip()\n",
    "    text = re.sub(r\"\\s+\", \" \", text)\n",
    "    if remove_punctuation:\n",
    "        text = re.sub(r\"[^\\w\\s]\", \" \", text, flags=re.UNICODE)\n",
    "        text = re.sub(r\"\\s+\", \" \", text)\n",
    "    return text.strip()\n",
    "\n",
    "\n",
    "def normalize_phone(value):\n",
    "    if is_missing(value):\n",
    "        return \"\"\n",
    "    return re.sub(r\"\\D+\", \"\", str(value))\n",
    "\n",
    "\n",
    "def normalize_website(value):\n",
    "    if is_missing(value):\n",
    "        return \"\"\n",
    "    text = str(value).lower().strip()\n",
    "    text = re.sub(r\"^https?://\", \"\", text)\n",
    "    text = re.sub(r\"^www\\.\", \"\", text)\n",
    "    text = text.split(\"/\")[0]\n",
    "    return text.rstrip(\"/\").strip()\n",
    "\n",
    "\n",
    "ROLE_NORMALIZERS = {\n",
    "    \"name\": normalize_text,\n",
    "    \"address\": normalize_text,\n",
    "    \"city\": normalize_text,\n",
    "    \"state\": normalize_text,\n",
    "    \"country\": normalize_text,\n",
    "    \"postal_code\": normalize_text,\n",
    "    \"phone\": normalize_phone,\n",
    "    \"website\": normalize_website,\n",
    "}\n",
    "\n",
    "for role, normalizer in ROLE_NORMALIZERS.items():\n",
    "    s1_col = f\"s1_{role}\"\n",
    "    matched_col = f\"matched_{role}\"\n",
    "    if s1_col not in pairwise_inspection.columns or matched_col not in pairwise_inspection.columns:\n",
    "        continue\n",
    "\n",
    "    s1_raw = pairwise_inspection[s1_col]\n",
    "    matched_raw = pairwise_inspection[matched_col]\n",
    "    s1_norm = s1_raw.map(normalizer)\n",
    "    matched_norm = matched_raw.map(normalizer)\n",
    "    both_present = s1_norm.ne(\"\") & matched_norm.ne(\"\")\n",
    "\n",
    "    pairwise_inspection[f\"{role}_both_present\"] = both_present\n",
    "    pairwise_inspection[f\"{role}_raw_exact\"] = both_present & s1_raw.fillna(\"\").astype(str).str.strip().eq(\n",
    "        matched_raw.fillna(\"\").astype(str).str.strip()\n",
    "    )\n",
    "    pairwise_inspection[f\"{role}_exact\"] = both_present & s1_norm.eq(matched_norm)\n",
    "\n",
    "comparison_cols = [\n",
    "    col\n",
    "    for col in pairwise_inspection.columns\n",
    "    if col.endswith(\"_exact\") or col.endswith(\"_both_present\")\n",
    "]\n",
    "front_cols = [\n",
    "    \"sample_group\",\n",
    "    \"s1_entity_id\",\n",
    "    \"matched_entity_id\",\n",
    "    \"matched_source\",\n",
    "    \"match_count\",\n",
    "]\n",
    "semantic_cols = [\n",
    "    col\n",
    "    for role in KEY_ROLES\n",
    "    for col in (f\"s1_{role}\", f\"matched_{role}\")\n",
    "    if col in pairwise_inspection.columns\n",
    "]\n",
    "display_cols = front_cols + semantic_cols + comparison_cols\n",
    "\n",
    "print(\"Inspection-friendly pairwise DataFrame with indicators:\")\n",
    "display(pairwise_inspection[display_cols])\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 6 - Readable Case Display\n",
    "\n",
    "Print each sampled S1 entity together with all of its positive S2/S3 ground-truth matches."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "def format_value(value):\n",
    "    if is_missing(value):\n",
    "        return \"(missing)\"\n",
    "    return str(value)\n",
    "\n",
    "\n",
    "def print_pairwise_record(row, prefix):\n",
    "    printed = False\n",
    "    for role in KEY_ROLES:\n",
    "        col = f\"{prefix}_{role}\"\n",
    "        if col in row.index:\n",
    "            print(f\"{role.replace('_', ' ').title()}: {format_value(row[col])}\")\n",
    "            printed = True\n",
    "    if not printed:\n",
    "        print(\"No detected semantic fields for this record.\")\n",
    "\n",
    "\n",
    "def display_positive_cases(pairwise_df, max_cases=25):\n",
    "    case_ids = pairwise_df[\"s1_entity_id\"].drop_duplicates().head(max_cases)\n",
    "    for s1_id in case_ids:\n",
    "        case = pairwise_df[pairwise_df[\"s1_entity_id\"] == s1_id].copy()\n",
    "        first = case.iloc[0]\n",
    "\n",
    "        print(\"=\" * 80)\n",
    "        print(f\"S1: {s1_id}\")\n",
    "        print(f\"Sample group: {first['sample_group']}\")\n",
    "        print(f\"Number of ground-truth matches: {int(first['match_count'])}\")\n",
    "        print(\"\\nSOURCE 1\")\n",
    "        print_pairwise_record(first, \"s1\")\n",
    "\n",
    "        for i, (_, match_row) in enumerate(case.iterrows(), start=1):\n",
    "            print(f\"\\nMATCH {i} - {match_row['matched_entity_id']} ({match_row['matched_source']})\")\n",
    "            print_pairwise_record(match_row, \"matched\")\n",
    "\n",
    "        print(\"=\" * 80)\n",
    "        print()\n",
    "\n",
    "\n",
    "display_positive_cases(pairwise_inspection, max_cases=25)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Step 7 - Basic Agreement Statistics and Manual-Inspection Flags\n",
    "\n",
    "Summarize normalized exact agreement across true positive links. Treat this as exploratory only: 25 S1 examples are enough to guide inspection, not enough for strong conclusions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "exact_cols = [\n",
    "    col\n",
    "    for col in [\"name_exact\", \"address_exact\", \"phone_exact\", \"website_exact\", \"country_exact\"]\n",
    "    if col in pairwise_inspection.columns\n",
    "]\n",
    "both_present_cols = [col for col in pairwise_inspection.columns if col.endswith(\"_both_present\")]\n",
    "\n",
    "if exact_cols:\n",
    "    agreement_summary = (\n",
    "        pairwise_inspection[exact_cols]\n",
    "        .mean()\n",
    "        .mul(100)\n",
    "        .round(2)\n",
    "        .rename(\"percent_of_positive_links\")\n",
    "        .to_frame()\n",
    "    )\n",
    "    print(\"Overall normalized exact-agreement rates:\")\n",
    "    display(agreement_summary)\n",
    "\n",
    "    print(\"Normalized exact-agreement rates by matched source:\")\n",
    "    display(pairwise_inspection.groupby(\"matched_source\")[exact_cols].mean().mul(100).round(2))\n",
    "else:\n",
    "    print(\"No comparable fields were detected in both S1 and matched sources.\")\n",
    "\n",
    "if both_present_cols:\n",
    "    missing_summary = (\n",
    "        (1 - pairwise_inspection[both_present_cols].mean())\n",
    "        .mul(100)\n",
    "        .round(2)\n",
    "        .rename(\"percent_one_or_both_missing\")\n",
    "        .to_frame()\n",
    "    )\n",
    "    print(\"Missingness across compared fields:\")\n",
    "    display(missing_summary)\n",
    "\n",
    "pattern_rows = []\n",
    "\n",
    "\n",
    "def add_pattern(label, mask):\n",
    "    pattern_rows.append({\n",
    "        \"pattern\": label,\n",
    "        \"link_count\": int(mask.sum()),\n",
    "        \"percent_of_sampled_positive_links\": round(float(mask.mean() * 100), 2) if len(mask) else 0.0,\n",
    "    })\n",
    "\n",
    "\n",
    "if {\"name_exact\", \"address_exact\", \"address_both_present\"}.issubset(pairwise_inspection.columns):\n",
    "    add_pattern(\n",
    "        \"Same normalized name + different normalized address\",\n",
    "        pairwise_inspection[\"name_exact\"] & pairwise_inspection[\"address_both_present\"] & ~pairwise_inspection[\"address_exact\"],\n",
    "    )\n",
    "\n",
    "if {\"name_exact\", \"address_exact\", \"name_both_present\"}.issubset(pairwise_inspection.columns):\n",
    "    add_pattern(\n",
    "        \"Different normalized name + same normalized address\",\n",
    "        pairwise_inspection[\"address_exact\"] & pairwise_inspection[\"name_both_present\"] & ~pairwise_inspection[\"name_exact\"],\n",
    "    )\n",
    "\n",
    "if {\"phone_exact\", \"name_exact\", \"name_both_present\"}.issubset(pairwise_inspection.columns):\n",
    "    add_pattern(\n",
    "        \"Same normalized phone + different normalized name\",\n",
    "        pairwise_inspection[\"phone_exact\"] & pairwise_inspection[\"name_both_present\"] & ~pairwise_inspection[\"name_exact\"],\n",
    "    )\n",
    "\n",
    "if {\"website_exact\", \"address_exact\", \"address_both_present\"}.issubset(pairwise_inspection.columns):\n",
    "    add_pattern(\n",
    "        \"Same normalized website/domain + different normalized address\",\n",
    "        pairwise_inspection[\"website_exact\"] & pairwise_inspection[\"address_both_present\"] & ~pairwise_inspection[\"address_exact\"],\n",
    "    )\n",
    "\n",
    "if {\"address_exact\", \"address_raw_exact\"}.issubset(pairwise_inspection.columns):\n",
    "    add_pattern(\n",
    "        \"Address formatting/punctuation differences only\",\n",
    "        pairwise_inspection[\"address_exact\"] & ~pairwise_inspection[\"address_raw_exact\"],\n",
    "    )\n",
    "\n",
    "for role in [\"address\", \"phone\", \"website\"]:\n",
    "    col = f\"{role}_both_present\"\n",
    "    if col in pairwise_inspection.columns:\n",
    "        add_pattern(\n",
    "            f\"Missing {role.replace('_', ' ')} in S1 or matched record\",\n",
    "            ~pairwise_inspection[col],\n",
    "        )\n",
    "\n",
    "if {\"country_both_present\", \"country_exact\"}.issubset(pairwise_inspection.columns):\n",
    "    add_pattern(\n",
    "        \"Different normalized country\",\n",
    "        pairwise_inspection[\"country_both_present\"] & ~pairwise_inspection[\"country_exact\"],\n",
    "    )\n",
    "\n",
    "pattern_summary = pd.DataFrame(pattern_rows).sort_values(\n",
    "    [\"link_count\", \"pattern\"], ascending=[False, True]\n",
    ")\n",
    "print(\"Recurring exploratory patterns:\")\n",
    "display(pattern_summary)\n",
    "\n",
    "manual_flag_masks = []\n",
    "manual_flag_labels = []\n",
    "\n",
    "if not lookup_issues_df.empty:\n",
    "    print(\"Lookup issues to inspect manually:\")\n",
    "    display(lookup_issues_df)\n",
    "\n",
    "if {\"country_both_present\", \"country_exact\"}.issubset(pairwise_inspection.columns):\n",
    "    manual_flag_masks.append(pairwise_inspection[\"country_both_present\"] & ~pairwise_inspection[\"country_exact\"])\n",
    "    manual_flag_labels.append(\"different_country\")\n",
    "\n",
    "if exact_cols:\n",
    "    manual_flag_masks.append(~pairwise_inspection[exact_cols].any(axis=1))\n",
    "    manual_flag_labels.append(\"no_exact_match_on_detected_key_fields\")\n",
    "\n",
    "if manual_flag_masks:\n",
    "    manual_flags = pd.Series(\"\", index=pairwise_inspection.index, dtype=\"object\")\n",
    "    for label, mask in zip(manual_flag_labels, manual_flag_masks):\n",
    "        manual_flags = manual_flags.mask(mask, manual_flags + np.where(manual_flags.eq(\"\"), label, \"; \" + label))\n",
    "\n",
    "    flagged_cases = pairwise_inspection.loc[manual_flags.ne(\"\"), display_cols].copy()\n",
    "    flagged_cases.insert(0, \"manual_flag\", manual_flags[manual_flags.ne(\"\")])\n",
    "    print(\"Suspicious or ambiguous sampled links for manual inspection:\")\n",
    "    if flagged_cases.empty:\n",
    "        print(\"No suspicious sampled links flagged by the simple rules above.\")\n",
    "    else:\n",
    "        display(flagged_cases)\n",
    "else:\n",
    "    print(\"No manual flag rules could be applied with the detected fields.\")\n",
    "\n",
    "print(\"Task 1 complete. Stop here before candidate generation, blocking, fuzzy matching, embeddings, thresholds, or modeling.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "pygments_lexer": "ipython3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}