# -*- coding: utf-8 -*-
"""1_EDA─ 02_task1_match_analysis ── 03_candidate_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17lDxsI2-7qi_rp2Tl9r96zvN3Umm7QiM
"""

import pandas as pd

s1 = pd.read_csv(
    "/content/train_source1.tsv",
    sep="\t"
)

s2 = pd.read_csv(
    "/content/train_source2.tsv",
    sep="\t"
)

s3 = pd.read_csv(
    "/content/train_source3.tsv",
    sep="\t"
)

gt = pd.read_csv(
    "/content/train_ground_truth.tsv",
    sep="\t"
)

print(s1.shape)
print(s2.shape)
print(s3.shape)
print(gt.shape)

display(s1.head())
display(s2.head())
display(s3.head())
display(gt.head())

s1.info()
s2.info()
s3.info()

print(s1.isnull().sum())
print(s2.isnull().sum())
print(s3.isnull().sum())

print(s1["country"].value_counts(dropna=False))

# step3

print(gt.shape)
print(gt.head(10))
print(gt.info())
print(gt.isnull().sum())

gt["match_count"] = gt["matched_entity_ids"].apply(
    lambda x: 0 if pd.isna(x) or x == "" else len(x.split(","))
)

print(gt["match_count"].value_counts().sort_index())

print(gt["match_count"].describe())

print("Singletons:", (gt["match_count"] == 0).sum())
print("1 match:", (gt["match_count"] == 1).sum())
print("2 matches:", (gt["match_count"] == 2).sum())
print("3+ matches:", (gt["match_count"] >= 3).sum())

from collections import Counter

source_counts = Counter()

for ids in gt["matched_entity_ids"].dropna():
    if ids == "":
        continue

    for entity_id in ids.split(","):
        if entity_id.startswith("S2-"):
            source_counts["S2"] += 1
        elif entity_id.startswith("S3-"):
            source_counts["S3"] += 1

print(source_counts)

# data creation (step 4)

samples_1 = gt[gt["match_count"] == 1].sample(
    5, random_state=42
)

samples_2 = gt[gt["match_count"] == 2].sample(
    5, random_state=42
)

samples_3_5 = gt[
    gt["match_count"].between(3, 5)
].sample(
    10, random_state=42
)

samples_6plus = gt[
    gt["match_count"] >= 6
].sample(
    5, random_state=42
)

sample_entities = pd.concat([
    samples_1,
    samples_2,
    samples_3_5,
    samples_6plus
])

print(sample_entities)

row = sample_entities.iloc[0]

s1_id = row["source1_entity_id"]
matched_ids = row["matched_entity_ids"].split(",")

print("S1 ID:", s1_id)
print("Matched IDs:", matched_ids)

s1[s1["entity_id"] == s1_id]

s2_ids = [x for x in matched_ids if x.startswith("S2-")]
s3_ids = [x for x in matched_ids if x.startswith("S3-")]

display(s2[s2["entity_id"].isin(s2_ids)])
display(s3[s3["entity_id"].isin(s3_ids)])